# Generated by Django 2.2.9 on 2020-01-31 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TMF', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=50)),
                ('exchange', models.CharField(max_length=25)),
                ('current_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('change_is_positive', models.BooleanField()),
                ('change_dollar', models.DecimalField(decimal_places=2, max_digits=10)),
                ('change_percent', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
    ]
