# Generated by Django 2.2.9 on 2020-02-02 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TMF', '0002_quote'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='symbol',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name='quote',
            name='website',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
