# Generated by Django 2.2.9 on 2020-02-03 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TMF', '0003_auto_20200202_1102'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='sfr_content',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='quote',
            name='symbol',
            field=models.CharField(max_length=15),
        ),
    ]
