# Generated by Django 2.2.9 on 2020-02-04 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TMF', '0005_auto_20200203_1617'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='test',
            field=models.TextField(blank=True),
        ),
    ]
