# Generated by Django 2.2.9 on 2020-02-05 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TMF', '0006_article_test'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quote',
            name='website',
        ),
        migrations.AddField(
            model_name='quote',
            name='detail_url',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='quote',
            name='image_url',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
