# Generated by Django 2.2.9 on 2020-02-05 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TMF', '0007_auto_20200205_1230'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='publish_at',
        ),
    ]
