# Generated by Django 2.2.9 on 2020-02-07 23:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('TMF', '0009_auto_20200207_1801'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='modified',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
