# Generated by Django 2.2.9 on 2020-02-10 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TMF', '0010_auto_20200207_1802'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='image_url',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
