# Generated by Django 2.2.9 on 2020-02-11 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TMF', '0011_article_image_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='body',
        ),
        migrations.AddField(
            model_name='article',
            name='body_extras',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='article',
            name='body_first_p',
            field=models.TextField(blank=True),
        ),
    ]
