# Generated by Django 2.2.9 on 2020-02-11 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TMF', '0012_auto_20200211_0959'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='body_extras',
            field=models.TextField(),
        ),
    ]
