# Generated by Django 2.2.9 on 2020-02-13 00:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TMF', '0013_auto_20200211_1512'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='test',
        ),
    ]
