# Generated by Django 2.2.9 on 2020-03-05 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TMF', '0014_remove_article_test'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='industry',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='quote',
            name='sector',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
